[workspace]
resolver = "3"
members = ["crates/bubbler-core", "crates/bubbler", "crates/bubbler-init"]

[workspace.package]
version = "0.3.0"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/han-xyz/bubbler"

[workspace.dependencies]
bubbler-core = { path = "crates/bubbler-core" }
bubbler-init = { path = "crates/bubbler-init" }
kdl = "6"
thiserror = "2"
rustix = { version = "1", features = ["fs", "process", "net", "pipe", "event", "pty", "termios"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
signal-hook = "0.3"
seccompiler = "0.5"
tempfile = "3"
