[package]
name = "bubbler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "bubblewrap-based application sandbox with instances and resource services"

[dependencies]
bubbler-core.workspace = true
clap.workspace = true
clap_mangen.workspace = true
anyhow.workspace = true
rustix.workspace = true

[dev-dependencies]
tempfile.workspace = true
